{% set name = "ollama" %}
{% set version = "0.5.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ollama-{{ version }}.tar.gz
  sha256: 7a575a90416a816231f216dbd10c3480b107218a90388c061fdf20d7ab7fe990

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.27
    - pydantic >=2.9.0

test:
  imports:
    - ollama
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ollama/ollama-python
  summary: The official Python client for Ollama.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
    - asmeurer
