{% set name = "ollama" %}
{% set version = "0.4.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ollama-{{ version }}.tar.gz
  sha256: e7fb71a99147046d028ab8b75e51e09437099aea6f8f9a0d91a71f787e97439e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.27.0,<0.28.0
    - pydantic >=2.9.0,<3.0.0

test:
  imports:
    - ollama
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://ollama.ai
  summary: The official Python client for Ollama.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
