{% set name = "ollama" %}
{% set version = "0.4.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ollama-{{ version }}.tar.gz
  sha256: 5dffc826737a1d121c9ae371439cace20ab02ec4b0840fd55c56efa9a3fb3646

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.27.0,<0.28.0

test:
  imports:
    - ollama
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://ollama.ai
  summary: The official Python client for Ollama.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
